import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* Area Header dengan background */}
        <header className="bg-yellow-500 py-4">
          <div className="flex justify-between items-center">
            <Image
              src={"/images/logo.png"}
              width={320}
              height={320}
              alt="Logo"
            ></Image>
            <div className="flex justify-end">
              <h1 className="font-bold text-white text-2xl pr-4">Data Ruang</h1>
              <h2 className="font-bold text-white text-2xl pl-4 pr-4">Pinjam Ruang</h2>
            </div>
          </div>
        </header>
         {/* area content */}
        <section className="m-10">{children}</section>

        {/* area footer */}
        <footer className="text-center text-yellow-500" >
          Copyright &copy; 2025 Woops - ERuang UTI
        </footer>
      </body>
    </html>
  );
}
