import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Ruang UTI.user",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* Area Header dengan background */}
        <header className="bg-yellow-500 py-4 border-b border-black">
          <div className="flex justify-between items-center px-10">
            <Image
              src={"/images/logo.png"}
              width={320}
              height={320}
              alt="Logo"
            ></Image>
            <div className="flex justify-end">
              <Link
                href="/druang"
                className="font-bold text-white text-2xl pl-4 pr-4 transition-colors duration-200 hover:text-red-700"
                passHref
              >
                Data Ruang
              </Link>
                <Link
                href={"/pruang"}
                className="font-bold text-white text-2xl pl-4 pr-4 transition-colors duration-200 hover:text-red-700"
                >
                Pinjam Ruang
                </Link>
            </div>
          </div>
        </header>
         {/* area content */}
        <section className="m-10">{children}</section>

        {/* area footer */}
        <footer className="text-center text-yellow-500" >
          Copyright &copy; 2025 Woops - ERuang UTI
        </footer>
      </body>
    </html>
  );
}
